// Auto-generated from swagger
import { ref } from 'vue'

const ResponseDepartmentDtoFormData = ref<APIResponseDepartmentDto>({
   id: undefined,
   name: undefined,
   code: undefined,
   parentId: undefined,
   parent: undefined,
   leader: undefined,
   leaderId: undefined,
   sort: undefined,
   isEnable: undefined,
   createdAt: undefined,
   createdBy: undefined,
   createdId: undefined,
   updatedAt: undefined,
   updatedBy: undefined,
   updatedId: undefined,
   deletedAt: undefined,
   deletedBy: undefined,
   deletedId: undefined,
   remark: undefined,
})

const ResponseUserDtoFormData = ref<APIResponseUserDto>({
   id: undefined,
   username: undefined,
   password: undefined,
   name: undefined,
   avatar: undefined,
   email: undefined,
   mobile: undefined,
   sex: undefined,
   address: undefined,
   nativeAddress: undefined,
   idCard: undefined,
   isEnable: undefined,
   lastLoginAt: undefined,
   loginFailCount: undefined,
   loginLockedUnitl: undefined,
   joinTime: undefined,
   leaveTime: undefined,
   department: undefined,
   departmentId: undefined,
   position: undefined,
   positionId: undefined,
   education: undefined,
   graduateSchool: undefined,
   emergencyContacts: undefined,
   emergencyContactPhone: undefined,
   idPhoto: undefined,
   bankCard: undefined,
   bankCardPhoto: undefined,
   resume: undefined,
   politicalStatus: undefined,
   status: undefined,
   birthday: undefined,
   createdAt: undefined,
   createdBy: undefined,
   createdId: undefined,
   updatedAt: undefined,
   updatedBy: undefined,
   updatedId: undefined,
   deletedAt: undefined,
   deletedBy: undefined,
   deletedId: undefined,
   remark: undefined,
})
