// Auto-generated from swagger
import { ref } from 'vue'

const CreateDepartmentDtoFormData = ref<ResponseCreateDepartmentDtoDto>({
   name: null,
   code: null,
   parentId: null,
   parent: null,
   leader: null,
   leaderId: null,
   sort: null,
   isEnable: null,
   createdAt: null,
   createdBy: null,
   createdId: null,
   updatedAt: null,
   updatedBy: null,
   updatedId: null,
   deletedAt: null,
   deletedBy: null,
   deletedId: null,
   remark: null,
})

const CreateUserDtoFormData = ref<ResponseCreateUserDtoDto>({
   username: null,
   password: null,
   name: null,
   avatar: null,
   email: null,
   mobile: null,
   sex: null,
   address: null,
   nativeAddress: null,
   idCard: null,
   isEnable: null,
   lastLoginAt: null,
   loginFailCount: null,
   loginLockedUnitl: null,
   joinTime: null,
   leaveTime: null,
   department: null,
   departmentId: null,
   position: null,
   positionId: null,
   education: null,
   graduateSchool: null,
   emergencyContacts: null,
   emergencyContactPhone: null,
   idPhoto: null,
   bankCard: null,
   bankCardPhoto: null,
   resume: null,
   politicalStatus: null,
   status: null,
   birthday: null,
   createdAt: null,
   createdBy: null,
   createdId: null,
   updatedAt: null,
   updatedBy: null,
   updatedId: null,
   deletedAt: null,
   deletedBy: null,
   deletedId: null,
   remark: null,
})
